# .gitlab-ci.yml

stages:
  - build

variables:
  INSTITUTE_NAME: "Pathnex"

build:
  stage: build
  image: maven:3.8.1-jdk-17

  script:
    - git clone https://github.com/Pathnex/sample-java-app.git
    - cd sample-java-app
    - echo "Welcome to $INSTITUTE_NAME DevOps Training"
    - mvn clean package -Dinstitute.name=$INSTITUTE_NAME