pipeline {
    agent any

    environment {
        INSTITUTE_NAME = "Pathnex"
    }

    stages {

        stage('Print') {
            steps {
                sh 'echo "Welcome to $INSTITUTE_NAME DevOps Training"'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -Dinstitute.name=$INSTITUTE_NAME'
            }
        }
    }
}