stages:
 - build

build: 
  stage: build
  image: maven:3.8.1-jdk-17

  cache:
    key: maven-cache
    paths:
      - .m2/repository
    
  script:
    - git clone https://github.com/Pathnex/sample-java-app.git
    - cd sample-java-app
    - mvn clean compile