pipeline {
    agent any

    environment {
        INSTITUTE_NAME = "Pathnex"
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/Pathnex/sample-java-app.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
    }

    post {
        success {
            mail(
                to: 'team@pathnex.com',
                subject: "SUCCESS: Build #${env.BUILD_NUMBER}",
                body: "Build completed successfully for $INSTITUTE_NAME"
            )
        }

        failure {
            mail(
                to: 'team@pathnex.com',
                subject: "FAILURE: Build #${env.BUILD_NUMBER}",
                body: "Build failed for $INSTITUTE_NAME"
            )
        }
    }
}