apiVersion: v1
kind: Pod

metadata:
  name: pathnex-sidecar

spec: 
  containers:
    - name: main
      image: nginx
      
    - name: sidecar
      image: busybox
      command:
        - sh
        - -c
        - "echo Sidecar running; sleep 3600"