stages:
  - deploy

variables:
  INSTITUTE_NAME: "Pathnex"

deploy-dev:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying $INSTITUTE_NAME to Dev environment"

deploy-staging:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying $INSTITUTE_NAME to Staging environment"
  when: manual

deploy-prod:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying $INSTITUTE_NAME to Prod environment"
  when: manual
