pipeline {
    agent any

    tools {
        nodejs 'NodeJS-16'
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/Pathnex/sample-node-app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
    }
}