pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Pathnex/sample-java-app.git'
            }
        }

        stage('List Files') {
            steps {
                sh 'ls -la'
            }
        }
    }
}