pipeline {
    agent any

    environment {
        INSTITUTE_NAME = "Pathnex"
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Promote') {
            steps {
                input message: 'Promote artifacts to staging?'
                sh 'echo "Promoting artifacts for $INSTITUTE_NAME"'
            }
        }
    }
}
