apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pathnex-db
spec:
  serviceName: pathnex
  replicas: 2
  selector:
    matchLabels:
      app: pathnex-db
  template:
    metadata:
      labels:
        app: pathnex-db
    spec:
      containers:
        - name: db
          image: mysql:8.4
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Pathnex123"
