pipeline {
    agent any

    environment {
        INSTITUTE_NAME = "Pathnex"
    }

    stages {
        stage('Build') {
            matrix {
                axes {
                    axis {
                        name 'JAVA_VERSION'
                        values '8', '11', '17'
                    }
                }

                stages {
                    stage('Build') {
                        steps {
                            sh "echo Building with Java $JAVA_VERSION"
                        }
                    }
                }
            }
        }
    }
}