pipeline {
    agent any

    parameters {
        string(
            name: 'ENVIRONMENT' ,
            defaultValue: 'dev',
            description: 'Deployment Environment'
        )
    }

    environment {
        INSTITUTE_NAME = "Pathnex"
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/Pathnex/sample-java-app.git'
            }
        }

        stage('Deploy') {
            steps {
                sh 'echo "Deploying to $ENVIRONMENT by $INSTITUTE_NAME"'
            }
        }
    }
}