pipeline {
    agent any

    environment {
        INSTITUTE_NAME = "Pathnex"
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/pathnex/sample-java-app.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Archive'){
            steps {
                archiveArtifacts(
                    artifacts: '**/target/*.jar',
                    fingerprint: true
                )
            }
        }
    }
}