# .gitlab-ci.yml

stages:
  - build-test

maven-build:
  stage: build-test
  image: maven:3.8.1-jdk-17

  script:
    - git clone https://github.com/Pathnex/sample-java-app.git
    - cd sample-java-app
    - mvn clean compile

maven-test:
  stage: build-test
  image: maven:3.8.1-jdk-17

  script:
    - git clone https://github.com/Pathnex/sample-java-app.git
    - cd sample-java-app
    - mvn test