pipeline {
    agent any

    stages {
        stage('Parallel Tasks') {
            parallel {

                stage('Build') {
                    steps {
                        sh 'mvn clean compile'
                    }
                }

                stage('Test') {
                    steps {
                        sh 'mvn test'
                    }
                }
            }
        }
    }
}