pipeline {
    agent any

    environment {
        INSTITUTE_NAME = 'Pathnex'
        TEAM           = 'DevOps'
        ENV            = 'prod'
    }

    triggers {
        pollSCM('H/15 * * * *')
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Pathnex/sample-java-app.git', branch: 'main'
            }
        }

        stage('Build') {
            when {
                buildingTag()
            }
            steps {
                sh 'echo "Building $INSTITUTE_NAME app for $TEAM team in $ENV environment"'
            }
        }
    }
}
