apiVersion: apps/v1
kind: Deployment

metadata: 
  name: pathnex-rolling

spec: 
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  selector:
    markLabels:
      app: roll

  template:
    metadata:
      labels:
        app: roll

    spec:
      containers:
        - name: web
          image: nginx
          