---
- name: Install Apache HTTP Server
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Deploy Pathnex HTTPD configuration
  ansible.builtin.template:
    src: pathnex.conf.j2
    dest: /etc/httpd/conf.d/pathnex.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart httpd

- name: Ensure Apache HTTP Server is running
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
