apiVersion: v1
kind: Pod

metadata:
  name: pathnex-probe-pod

spec:
  containers:
    - name: web
      image: nginx

      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5

      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDaySeconds: 3 